### PR TITLE
Matt/master/docdash

### PR DESCRIPTION
**Pull request by MareoRaft**
For issue #32

### CODE REVIEW

**Comment by MareoRaft** [comment]
This generates the docs using the docdash template instead of the default jsdoc template.  I think that's why the `fonts` folder, for example, went away.

**Comment by MareoRaft** [comment]
it should look like this now:

Screenshot 2019-05-14 15 45 26

**Comment by MareoRaft** [comment]
Not sure why this is failing.  It works locally on my mac.  Does it work locally for you?

**Comment by MareoRaft** [comment]
seems to only fail for latest version of node.  Wonder if updating `requizzle` or reporting this error to requizzle maintainer will help.  Let me know what you find out

**Comment by jankapunkt** [comment]
no worries about the fail this will be resolved in an own PR because I think this is rather a config issue with the CI server

**Review by jankapunkt — APPROVED** [review]

**Pull request merged**
